---
prelude: >
    Magnum's bay-to-cluster blueprint [1] required
    changes across much of its codebase to align to
    industry standards.

    To support this blueprint, certain group and option
    names were changed in configuration files [2].

    See the deprecations section for more details.

    [1] https://review.openstack.org/#/q/topic:bp/rename-bay-to-cluster
    [2] https://review.openstack.org/#/c/362660/

deprecations:
  - The 'bay' group has been renamed to 'cluster' and all
    options in the former 'bay' group have been moved to
    'cluster'.
  - The 'bay_heat' group has been renamed to 'cluster_heat'
    and all options in the former 'bay_heat' group have been
    moved to 'cluster_heat'.
  - The 'bay_create_timeout' option in the former 'bay_heat'
    group has been renamed to 'create_timeout' inside the
    'cluster_heat' group.
  - The 'baymodel' group has been renamed to 'cluster_template'
    and all options in the former 'baymodel' group have been
    moved to 'cluster_template'.
