#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0644"
    content: |
      KUBE_ALLOW_PRIV="$KUBE_ALLOW_PRIV"
      KUBE_MASTER_IP="$KUBE_MASTER_IP"
      KUBE_API_PORT="$KUBE_API_PORT"
      KUBE_NODE_PUBLIC_IP="$KUBE_NODE_PUBLIC_IP"
      KUBE_NODE_IP="$KUBE_NODE_IP"
      ETCD_SERVER_IP="$ETCD_SERVER_IP"
      ENABLE_CINDER="$ENABLE_CINDER"
      DOCKER_VOLUME="$DOCKER_VOLUME"
      DOCKER_STORAGE_DRIVER="$DOCKER_STORAGE_DRIVER"
      NETWORK_DRIVER="$NETWORK_DRIVER"
      REGISTRY_ENABLED="$REGISTRY_ENABLED"
      REGISTRY_PORT="$REGISTRY_PORT"
      SWIFT_REGION="$SWIFT_REGION"
      REGISTRY_CONTAINER="$REGISTRY_CONTAINER"
      REGISTRY_INSECURE="$REGISTRY_INSECURE"
      REGISTRY_CHUNKSIZE="$REGISTRY_CHUNKSIZE"
      TLS_DISABLED="$TLS_DISABLED"
      CLUSTER_UUID="$CLUSTER_UUID"
      MAGNUM_URL="$MAGNUM_URL"
      AUTH_URL="$AUTH_URL"
      USERNAME="$USERNAME"
      PASSWORD="$PASSWORD"
      VOLUME_DRIVER="$VOLUME_DRIVER"
      REGION_NAME="$REGION_NAME"
      TENANT_NAME="$TENANT_NAME"
      HTTP_PROXY="$HTTP_PROXY"
      HTTPS_PROXY="$HTTPS_PROXY"
      NO_PROXY="$NO_PROXY"
      WAIT_CURL="$WAIT_CURL"
      KUBE_VERSION="$KUBE_VERSION"
      TRUSTEE_USER_ID="$TRUSTEE_USER_ID"
      TRUSTEE_USERNAME="$TRUSTEE_USERNAME"
      TRUSTEE_PASSWORD="$TRUSTEE_PASSWORD"
      TRUSTEE_DOMAIN_ID="$TRUSTEE_DOMAIN_ID"
      TRUST_ID="$TRUST_ID"
      AUTH_URL="$AUTH_URL"
      INSECURE_REGISTRY_URL="$INSECURE_REGISTRY_URL"
